env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: cloudagent
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
    - "7"

archives:
  - replacements:
      386: i386
      amd64: x86_64
    files:
      - docs/
      - README.md
      - LICENSE

nfpms:
- maintainer: Filip Strózik <filip.strozik@outlook.com>
  description: The simple and easy-to-use program designed to watch user activity for Cloud Providers.
  homepage: https://github.com/pPrecel/cloudagent
  license: MIT
  formats:
  - deb
  - rpm
  - apk

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
