env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: cloudagent
    main: ./main.go
    ldflags:
      - -X "main.Version={{.ENV.GITHUB_REF_NAME}}"
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
    - "7"

archives:
  - replacements:
      386: i386
      amd64: x86_64
    files:
      - docs/
      - README.md
      - LICENSE

nfpms:
- maintainer: Filip Strózik <filip.strozik@outlook.com>
  description: The simple and easy-to-use program designed to watch user activity for Cloud Providers.
  homepage: https://github.com/pPrecel/cloudagent
  license: MIT
  formats:
  - deb
  - rpm
  - apk

brews:
  - homepage: "http://github.com/pPrecel/cloudagent"
    description: "The simple and easy-to-use program designed to watch user activity for Cloud Providers."
    tap:
      owner: pPrecel
      name: homebrew-tap
    goarm: "7"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    license: "MIT"
    test: |
      system "#{bin}/cloudagent"
    install: |
      bin.install "cloudagent"
    service: |
      run ["#{opt_bin}/cloudagent", "serve"]
      log_path "/tmp/cloudagent/cloudagent.stdout"
      environment_variables PATH: "/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:#{Dir.home}/.rd/bin:#{Dir.home}/.krew/bin:"
      keep_alive true

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
