env:
  - GO111MODULE=on

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    binary: cloudagent
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
    - "7"

archives:
  - replacements:
      386: i386
      amd64: x86_64
    files:
      - docs/
      - README.md
      - LICENSE

nfpms:
- maintainer: Filip Strózik <filip.strozik@outlook.com>
  description: The simple and easy-to-use program designed to watch user activity for Cloud Providers.
  homepage: https://github.com/pPrecel/cloudagent
  license: MIT
  formats:
  - deb
  - rpm
  - apk

brews:
  - homepage: "http://github.com/pPrecel/cloudagent"
    description: "The simple and easy-to-use program designed to watch user activity for Cloud Providers."
    tap:
      owner: pPrecel
      name: homebrew-tap
    goarm: "7"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    folder: Formula
    license: "MIT"
    test: |
      system "#{bin}/cloudagent"
    install: |
      bin.install "cloudagent"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
              <key>EnvironmentVariables</key>
              <dict>
                      <key>PATH</key>
                      <string>/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:</string>
              </dict>
              <key>Label</key>
              <string>com.pPrecel.cloudagent.agent.plist</string>
              <key>ProgramArguments</key>
              <array>
                      <string>/usr/local/bin/cloudagent</string>
                      <string>serve</string>
              </array>
              <key>RunAtLoad</key>
              <true/>
              <key>KeepAlive</key>
              <true/>
              <key>StandardOutPath</key>
              <string>/tmp/cloudagent/cloudagent.stdout</string>
      </dict>
      </plist>

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}"
changelog:
  sort: asc
