on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

name: build
jobs:

  build:
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - 
      uses: actions/checkout@v3
    - 
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - 
      uses: arduino/setup-protoc@v1
      with:
        version: '3.17.3'
    - 
      name: Verify
      run: make verify-ci
    - 
      name: Build
      run: make build
